name: ci
on: 

  # events execution
  push:
    branches:
      - main
  
  # programmed execution
  schedule:
    - cron:  '0 0 21 * *'
    
  # manual execution
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code 🛎
        uses: actions/checkout@v2

      - name: E2E & UI tests
        uses: cypress-io/github-action@v2
          
      - run: npm run report:merge
      - run: npm run report:mocha
  
  #github pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: mochawesome-report
